GET http://localhost:8080/test/sync
###
GET http://localhost:8080/test/async
###
POST http://localhost:8080/members/sign-up
content-type: application/json

{
  "name": "zayden"
}
###
POST http://localhost:8080/test/pubsub-adapter
